<?php
namespace IMSGlobal\Caliper\entities;

class EntityType extends \IMSGlobal\Caliper\util\BasicEnum implements Type {
    const
        __default = '',
        AGENT = 'Agent',
        AGGREGATE_MEASURE = 'AggregateMeasure',
        AGGREGATE_MEASURE_COLLECTION = 'AggregateMeasureCollection',
        ANNOTATION = 'Annotation',
        ASSESSMENT = 'Assessment',
        ASSESSMENT_ITEM = 'AssessmentItem',
        ATTEMPT = 'Attempt',
        AUDIO_OBJECT = 'AudioObject',
        BOOKMARK_ANNOTATION = 'BookmarkAnnotation',
        CHAPTER = 'Chapter',
        COLLECTION = 'Collection',
        COMMENT = 'Comment',
        COURSE_OFFERING = 'CourseOffering',
        COURSE_SECTION = 'CourseSection',
        DIGITAL_RESOURCE = 'DigitalResource',
        DIGITAL_RESOURCE_COLLECTION = 'DigitalResourceCollection',
        DOCUMENT = 'Document',
        ENTITY = 'Entity',
        FILLINBLANK = 'FillinBlankResponse',
        FORUM = 'Forum',
        GROUP = 'Group',
        HIGHLIGHT_ANNOTATION = 'HighlightAnnotation',
        IMAGE_OBJECT = 'ImageObject',
        LEARNING_OBJECTIVE = 'LearningObjective',
        LIKERT_SCALE = 'LikertScale',
        LINK = "Link",
        LTI_SESSION = 'LtiSession',
        LTI_LINK = "LtiLink",
        MEMBERSHIP = 'Membership',
        MESSAGE = 'Message',
        MULTIPLECHOICE = 'MultipleChoiceResponse',
        MULTIPLERESPONSE = 'MultipleResponseResponse',
        MULTISELECT_SCALE = 'MultiselectScale',
        NUMERIC_SCALE = 'NumericScale',
        ORGANIZATION = 'Organization',
        PAGE = 'Page',
        PERSON = 'Person',
        QUERY = 'Query',
        QUESTION = 'Question',
        RATING = 'Rating',
        RATING_SCALE_QUESTION = 'RatingScaleQuestion',
        RESPONSE = 'Response',
        RESULT = 'Result',
        SCALE = 'Scale',
        SCORE = 'Score',
        SEARCH_RESPONSE = 'SearchResponse',
        SELECTTEXT = 'SelectTextResponse',
        SESSION = 'Session',
        SHARED_ANNOTATION = 'SharedAnnotation',
        SOFTWARE_APPLICATION = 'SoftwareApplication',
        TAG_ANNOTATION = 'TagAnnotation',
        THREAD = 'Thread',
        TRUEFALSE = 'TrueFalseResponse',
        VIDEO_OBJECT = 'VideoObject',
        VIEW = 'View';
}